export const INIT_REPO_INFO_FETCH = 'INIT_REPO_INFO_FETCH';
export const SET_REPO_INFO = 'SET_REPO_INFO';
export const REPO_INFO_FETCH_ERROR_OCCURED = 'REPO_INFO_FETCH_ERROR_OCCURED';
export const INIT_ISSUES_PAGE_FETCH = 'INIT_ISSUES_PAGE_FETCH';
export const SET_ISSUES_BY_PAGE = 'SET_ISSUES_BY_PAGE';
